### ISSUE TITLE
Cannot read property 'workerSrc' of undefined

### ISSUE THREAD

**Issue by nbalaji27** [smith-carson/ember-pdf-js#15]
I tried to include this add-on in an our existing ember-cli build. Am getting an error Cannot read property 'workerSrc' of undefined. Can you please let me know, anything I have to include to make it run properly ?

The version which I have used is 0.1.12

<img width="834" alt="bff85d64-4af7-11e7-9883-bf0e8a046f8c" src="https://user-images.githubusercontent.com/7175074/27037144-addcacfa-4fa4-11e7-97e2-1c3bbc764274.png">
<img width="1305" alt="bff161a8-4af7-11e7-8444-4f919ae563e8" src="https://user-images.githubusercontent.com/7175074/27037145-ae025b62-4fa4-11e7-9664-c12213ea9b4b.png">

**Comment by marceloandrader** [comment]
@balun7 you need to set the path to the pdf.worker.js on the app, using the config/environment.js file

![screenshot from 2017-06-12 10-43-08](https://user-images.githubusercontent.com/57552/27042256-00e40c52-4f5c-11e7-983f-efaab439e95c.png)

**Comment by marceloandrader** [comment]
That file is installed with bower, after the installation of this addon, it should add a dependency to pdfjs-dist 1,7.316 on your bower.json.

**Comment by nbalaji27** [comment]
Hi @marceloandrader,

Thanks for your response, Even though including emberPdfJs object in my app config environment, Am receiving same error `Workersrc` undefined. 

<img width="959" alt="screen shot 2017-06-13 at 11 31 19 am" src="https://user-images.githubusercontent.com/7175074/27068093-dc9513c0-502b-11e7-8459-f3d2cb251a60.png">

Am I missing anything ?

**Comment by nbalaji27** [comment]
I identified the issue, Thanks!
