### ISSUE TITLE
Upgrade PDFJS Dist

### ISSUE THREAD

**Issue by gte451f** [smith-carson/ember-pdf-js#21]
We've been pinned to an older version of PDF JS for a while, can we consider upgrading it?
https://github.com/mozilla/pdf.js/releases

At the time, we pinned to a particular version to avoid some breaking changes.
https://github.com/smith-carson/ember-pdf-js/commit/4c2dc2560d5da2cc2105a07ed2f2283ef26ccc4b

**Comment by marceloandrader** [comment]
Fixed in #25
