### ISSUE TITLE
JPEG error: unexpected marker ffd9

### ISSUE THREAD

**Issue by islambek01** [smith-carson/ember-pdf-js#24]
Link to pdf file:
[Untitled_file](https://github.com/mozilla/pdf.js/files/601312/Untitled_20160807_114311.pdf)

Bug - It is showing blank page.

Console Error is below:
![screen-error](https://user-images.githubusercontent.com/32124707/77723444-ae108400-701a-11ea-8f83-5abce4159acd.png)

@andyhot

**Comment by marceloandrader** [comment]
@islambek01 Looks like an internal pdfjs error.

**Comment by islambek01** [comment]
> @islambek01 Looks like an internal pdfjs error.

@marceloandrader Yes.

**Comment by marceloandrader** [comment]
Fixed in #25

**Comment by marceloandrader** [comment]
@islambek01 @andyhot I've released 1.0.0 in npm

**Comment by islambek01** [comment]
> @islambek01 @andyhot I've released 1.0.0 in npm

@marceloandrader  Thank's a lot. The bug is resolved.

**Comment by andyhot** [comment]
Cool, though i didn't do anything, give @marceloandrader all the credit !
