### ISSUE TITLE
`broccoli-merge-trees` should be a dependency, not devDependency

### ISSUE THREAD

**Issue by justwright** [smith-carson/ember-pdf-js#6]
As soon as I ran `ember install` for this addon, I received this error: `Cannot find module 'broccoli-merge-trees'`, which I believe would be resolved by moving `broccoli-merge-trees` to the dependencies area of addon's package.json instead of the devDependencies area

**Comment by leojpod** [comment]
Should be fixed in the [new version](https://github.com/smith-carson/ember-pdf-js/releases/tag/v0.1.7)
